//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementSystem
{
    public partial class TrackStatus
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        // Main token info panel
        protected global::System.Web.UI.WebControls.Panel pnlTokenInfo;

        // Token card labels
        protected global::System.Web.UI.WebControls.Label lblTokenNumber;
        protected global::System.Web.UI.WebControls.Label lblBusinessType;

        // Status details labels
        protected global::System.Web.UI.WebControls.Label lblCustomerName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl rowReason;
        protected global::System.Web.UI.WebControls.Label lblReason;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblPosition;
        protected global::System.Web.UI.WebControls.Label lblWaitTime;

        // Message box labels
        protected global::System.Web.UI.WebControls.Label lblMsgIcon;
        protected global::System.Web.UI.WebControls.Label lblMessage;

        // Payment section controls
        protected global::System.Web.UI.WebControls.Panel pnlPaymentSection;
        protected global::System.Web.UI.WebControls.Panel pnlPayment;
        protected global::System.Web.UI.WebControls.Label lblPaymentStatus;
        protected global::System.Web.UI.WebControls.Image imgQR;
        protected global::System.Web.UI.WebControls.HyperLink lnkGPay;
        protected global::System.Web.UI.WebControls.HyperLink lnkPhonePe;
        protected global::System.Web.UI.WebControls.HyperLink lnkPaytm;
        protected global::System.Web.UI.WebControls.Button btnConfirmPayment;

        // Payment done panel
        protected global::System.Web.UI.WebControls.Panel pnlPaymentDone;

        // Error panel
        protected global::System.Web.UI.WebControls.Panel pnlError;
    }
}
