//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementSystem.Restaurant
{


    public partial class Dashboard
    {

        /// <summary>
        /// lblTotalTokens control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalTokens;

        /// <summary>
        /// lblActiveOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveOrders;

        /// <summary>
        /// lblCompleted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCompleted;

        /// <summary>
        /// lblPaymentPending control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaymentPending;

        /// <summary>
        /// rptActiveOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActiveOrders;

        /// <summary>
        /// pnlNoOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoOrders;
    }
}
