//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementSystem.Restaurant
{


    public partial class NewToken
    {

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlTokenGenerated control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTokenGenerated;

        /// <summary>
        /// lblTokenNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTokenNumber;

        /// <summary>
        /// lblConfirmName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConfirmName;

        /// <summary>
        /// txtCustomerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCustomerName;

        /// <summary>
        /// rfvName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;

        /// <summary>
        /// txtTableNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTableNumber;

        /// <summary>
        /// rfvTable control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTable;

        /// <summary>
        /// txtContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContact;

        /// <summary>
        /// btnGenerateToken control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGenerateToken;

        /// <summary>
        /// imgQR control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgQR;

        /// <summary>
        /// lblTrackURL control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTrackURL;

        /// <summary>
        /// btnNewToken control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNewToken;
    }
}
