//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementSystem.Restaurant
{


    public partial class OrderStatus
    {

        /// <summary>
        /// rptOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOrders;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
